### PR TITLE
add nft marketplaces coresky

### PR DESCRIPTION
**Pull request by csgithub007**
add nft marketplaces coresky

### CODE REVIEW

**Comment by slasher125** [comment]
hi, ty for adding. can u confirm that its a fork of seaport?

**Comment by jason0513** [comment]
I modified it according to the opensea code, and the contract address is different. So what do I do next?

**Comment by slasher125** [comment]
the abi seems wrong (should be the abi from the contract u defined in config.json)

**Comment by csgithub007** [comment]
We have modified the ABI.

**Pull request merged**
